### ISSUE TITLE
dependencies - scour

### ISSUE THREAD

**Issue by laureanorp** [shuttle99ou/Flask-Image-Resizer#11]
Tried to remove `scour` from our project dependencies and resulted in a failed build because Flask Image Resizer requires it:

https://app.circleci.com/pipelines/github/shuttle99ou/misolvencia/9720/workflows/44a2bea5-34b8-439b-b2cb-93879539549a/jobs/19059

It should be added here and removed form our other project, right?

**Comment by urshulgi** [comment]
Done in #12. Also pinned the other requirements.
