### ISSUE TITLE
PIL.Image.ANTIALIAS is deprecated

### ISSUE THREAD

**Issue by urshulgi** [shuttle99ou/Flask-Image-Resizer#9]
```
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

https://stackoverflow.com/a/76616129

From github:

> ANTIALIAS was removed in Pillow 10.0.0 (after being deprecated through many previous versions). Now you need to use PIL.Image.LANCZOS or PIL.Image.Resampling.LANCZOS.
> (This is the exact same algorithm that ANTIALIAS referred to, you just can no longer access it through the name ANTIALIAS.)

Should we update this?

**Comment by jllopezpino** [comment]
Yes. Let's update

**Comment by urshulgi** [comment]
Done in #12 with the update to 3.0.6
